# Generated by Django 6.0 on 2026-01-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cnic', models.CharField(max_length=33)),
                ('Father_name', models.CharField(max_length=33)),
            ],
        ),
    ]
